Move script templates dir, replace stock template, fix override in Skeleton, and other misc. cleanup
HazDroneCorp/combat-engineers pull request #94
Opened 2021-05-21 19:44 UTC by SuscipiamSingularitatem

script templates dir is #72

2021-05-21 23:34 UTC, HazmatDrone approved these changes

2021-05-21 23:34 UTC, HazmatDrone commented on ui/Console.cs
> +help: this text",
But why

2021-05-22 07:07 UTC, Krutonium commented on ui/Console.cs
> +help: this text",
Doesn't matter any more; File should be excluded.

2021-05-22 09:42 UTC, Krutonium commented on ui/Console.cs
> +help: this text",
Why even this change, anyway? Regardless, this file has been replaced in a different PR, so this should either but updated to the new file or excluded.

2021-05-23 00:12 UTC, HazmatDrone requested changes
Please drop changes to `ui/Console.cs`

2021-05-23 18:34 UTC, Krutonium commented
I added an editorconfig based on the coding style seen in this PR. It will of course need tweaking, but it should help enforce the code style.

2021-05-24 03:06 UTC, HazmatDrone commented on ui/Console.cs
>  					}
```suggestion
				} else  if (Player is null) {
					PrintToConsole("Can't find the player!", true);
					break;
				}
```

2021-05-24 12:21 UTC, HazmatDrone commented
@Krutonium can review and merge this if he's happy with it

2021-05-25 03:47 UTC, Krutonium commented
I see nothing that needs changes, OK to merge.

2021-05-25 03:48 UTC, Krutonium approved these changes
Looks  Good

2021-05-25 03:48 UTC, merged